# Numpy 정리
Numpy의 공식 문서를 보고 정리합니다.

- [공식 문서](https://numpy.org/doc/stable/contents.html)

NumPy에 대한 설명 [링크](https://numpy.org/doc/stable/user/whatisnumpy.html)
- 대충 번역해보면 파이썬에서 다차원 배열, 즉 여러 디멘션을 계산, 생성, 처리하기 위한 다양한 자료형과 메소드를 제공하는 라이브러리.

NumPy의 특징
- 일단 Python List와 다르게 NumPy의 Arrray는 fixed size이다.
- NumPy Array의 모든 값은 모두 같은 자료형을 가져야한다. 또한 메모리에서 같은 사이즈여야한다.
- NumPy Array는 큰 수의 여러가지 수학적인 동작들을 용이하게 한다. 보통 파이썬의 Built-In된 시퀀스로도 처리가능하긴 하다.

## Quickstart Tutorial

- `ndarray.ndim` : 배열의 dimensions 수
- `ndarray.shape` : 매트릭스면 (row, column)인데 이 인자 수는 차원에 비례함
- `ndarray.size` : 요소의 총합, product의 곱과 같다고 함
- `ndarray.dtype` : 데이터타입
- `ndarray.itemsize` : 아이템 하나의 byte size
- `ndarray.data`(사용안함) : 실제 array 요소들을 가지고 있는 버퍼

In [121]:
import numpy as np

In [122]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [123]:
a = np.arange(20).reshape(4, 5)
a.shape

(4, 5)

In [124]:
a = np.arange(20).reshape(4, 5)
a.ndim

2

In [125]:
a = np.arange(20).reshape(4, 5)
a.dtype.name

'int32'

In [126]:
a = np.arange(20).reshape(4, 5)
a.itemsize

4

In [127]:
# 쓸일 없음
a = np.arange(20).reshape(4, 5)
a.data

In [128]:
# 3차원
b = np.arange(20).reshape(2, 2, 5)
b
# b.shape
# b.ndim
# b.dtype.name
# b.itemsize
# b.size

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [129]:
# Python 리스트로부터 NumPy array 만들기
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [130]:
# 0 으로 채워진 배열
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
# 1부터 10까지 2씩 증가
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [132]:
# 모두 출력
# np.set_printoptions(threshold=sys.maxsize)
# np.set_printoptions(threshold=10)
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [135]:
# Basic Operations
# NumPy Array 기본적인 행렬 연산이 가능함
# 정말 다양한 연산(삼각함수, 행렬, 지수, 집합함수 등)이 가능하고 좋은 레퍼런스는 아래 링크
# https://rfriend.tistory.com/294?category=675917
# 찾아보니 데이터 전처리에 이용되는 차원 확장과 축소도 NumPy로 가능
a = np.array([20, 30, 40, 50])
b = np.array([0, 1, 2, 3])

print(a + b)  # 요소간 덧셈
print(a - b)  # 요소간 뺄셈
print(b**2)   # 요소에 제곱
print(np.sin(a)) # 요소에 사인함수
print(np.cos(a)) # 요소에 코사인함수
print(np.tan(a)) # 요소에 탄젠트함수
print(a < 35)    # 요소마다 Boolean으로 결과나옴

# NumPy Array는 자동 형번환이 안되기 때문에 NumPy Array간 연산을 할 때 dType을 맞춰주어야함

[20 31 42 53]
[20 29 38 47]
[0 1 4 9]
[ 0.91294525 -0.98803162  0.74511316 -0.26237485]
[ 0.40808206  0.15425145 -0.66693806  0.96496603]
[ 2.23716094 -6.4053312  -1.11721493 -0.27190061]
[ True  True False False]
[  0  30  80 150]
260
260
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [ ]:
## 곱셈
print(a * b) # 요소간 곱셈
print(a @ b) # 행렬곱
print(a.dot(b)) # 행렬곱

In [138]:
# 집계 함수
c = np.arange(12).reshape(3, 4)
print(c)

# axis 는 방향, 0 = column, 1 = row
print(c.sum(axis=0))
print(c.sum(axis=1))

print(c.max(axis=0))
print(c.min(axis=1))

print(c.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
[ 8  9 10 11]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [ ]:
# Universal Functions
# np.exp() 자연상수 e^x꼴로 만들어주는 함수
b = np.arange(3)
print(np.exp(b))
print(np.sqrt(b))

In [140]:
# Indexing, Slicing and Iterating

# 1차원에서는 파이썬 리스트처럼 사용가능
a = np.arange(10) ** 3
print(a)
print(a[2:6:2])

[  0   1   8  27  64 125 216 343 512 729]
[ 8 64]


In [146]:
# 2차원에서는 axis별로 인덱스를 가짐
# 슬라이싱할 때 콤마로 구분하는데, dot(...)으로 생략 가능함
a = np.arange(10).reshape(2, 5)
print(a)
print(a[:1,:2])

print("===========")
print(a[:1,:])
print(a[:1,...])

# flat을 사용하면 1 dimension처럼 iterate할 수 있음
# print(a.flat)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]]
[[0 1 2 3 4]]
[[0 1 2 3 4]]


In [147]:
# Shape Manipulation
rg = np.random
a = np.floor(10 * rg.random((3, 4)))
print(a)

print(a.ravel())
print(a.reshape(6, 2))
print(a.T) # 전치행렬


[[9. 0. 8. 7.]
 [6. 5. 9. 3.]
 [1. 4. 3. 6.]]
